name: sampleapi
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0-246.0.dev

# Add regular dependencies here.
dependencies:
  hive: ^2.2.3
  json_annotation: ^4.8.1

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  hive_generator: ^2.0.0
