openapi: 3.0.0
info:
  title: Api
  version: 0.0.0
servers:
  - url: "http://localhost:8080"
paths:
  /product:
    get:
      tags:
        - ProductsController
      summary: getProducts
      operationId: getProducts
      responses:
        200:
          description: "Operation completed!"
    post:
      tags:
        - ProductsController
      summary: createProduct
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductDTO"
      responses:
        200:
          description: "Operation completed!"
  /product/<id>:
    get:
      tags:
        - ProductsController
      summary: getProduct
      operationId: getProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
    put:
      tags:
        - ProductsController
      summary: updateProduct
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductDTO"
      responses:
        200:
          description: "Operation completed!"
    delete:
      tags:
        - ProductsController
      summary: deleteProduct
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: "Operation completed!"
components:
  schemas:
    ProductDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        photo:
          type: string
      required:
        - title
        - description
        - price
tags:
  - name: ProductsController